### PR TITLE
Fix SAST bug on recursive return type mismatch

### LINKED ISSUE #79: Return Type mismatch
@akalicki - we were talking about this earlier.

### PR DESCRIPTION
**Pull request by akalicki**
- fix bug when attempting to return a type other than that constrained in a recursive function
- add fail tests for recursive param and return type mismatches
- update readme to point to new travis build links
- general cleanup

Fixes #79. cc @dannyech

### CODE REVIEW

File: compiler/analyzer.ml [hunk 1]
```diff
@@ -506,20 +503,28 @@ and check_fdecl env id f anon =
...
 
   (* Unconstrained function return types are not allowed *)
   let Sast.Expr(_, ret_type) = return in
-  if ret_type = Any || ret_type = List(Unconst) then 
-    fdecl_unconst_error id 
+  let ret_type = match ret_type with
+    | Any -> fdecl_unconst_error id
+    | Unconst -> fdecl_unconst_error id
+    | List(Any) -> fdecl_unconst_error id
+    | _ as typ -> typ in
```
Comment (dannyech) [inline compiler/analyzer.ml]: @akalicki . What if we try to return a function whose return type is `Unconst`. Are you checking and prohibiting this case?

**Comment by dannyech** [comment]
Looks good to me, see the one comment I made. In addition, might not need to check for `Any` in the following snippet b/c of the changes i made in constrain_any:

```ocaml
let ret_type = match ret_type with
   | Any -> fdecl_unconst_error id
   | Unconst -> fdecl_unconst_error id
   | List(Any) -> fdecl_unconst_error id
   | _ as typ -> typ
```
checking for it doesn't hurt tho, so might as well keep it in since it's not breaking anything.

File: compiler/analyzer.ml (hunk 1 above)
Comment (akalicki) [inline compiler/analyzer.ml]: That actually gets caught by the `Unconst` case here, since the nested function gets recursively called into `check_fdecl` and will throw before we even try to return it.

**Comment by akalicki** [comment]
Great - I'll leave it in for now but we can remove it later if we want.

File: compiler/analyzer.ml (hunk 1 above)
Comment (dannyech) [inline compiler/analyzer.ml]: ah gotcha - nice!
